# -*- coding: utf-8 -*-
"""praw_reddit_setup_guide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/106PskjcTehZmxtCg59ucSBhp5DXF-Exh

**Install Dependencies**
"""

!pip install praw
!pip install flask

"""**Use Flask to handle incoming requests from redirect URI from Reddit**"""

from flask import Flask, request

app = Flask(__name__)

@app.route('/reddit_callback')
def reddit_callback():
    # Retrieve the authorization code or access token from the URL parameters
    authorization_code = request.args.get('code')
    # Do something with the authorization code, such as exchanging it for an access token
    # Or, store it for later use
    return "Callback received successfully"

if __name__ == '__main__':
    app.run(host='localhost', port=8088)

"""**Gather data from Reddit using PRAW**"""

# Step 1: pip install praw, pip install flask
# Step 2: Go to the Reddit apps page (https://www.reddit.com/prefs/apps) while logged into your Reddit account.
# Step 3: Click on “are you a developer? create an app...” or “create another app”.
#         Fill out the form:
#         Name your application.
#         Select the “script” option.
#         Note down the client ID (found underneath the app name), user agent (your username found above the app name), and the client secret.
# Step 4: Input them below, and then run the cell

import praw
import pandas as pd

reddit = praw.Reddit(
    client_id='mrzgumUG-od281mSE324tA',
    client_secret='c4A2ZYZuS55vvg4fyWrgVa09dF-3xg',
    user_agent='Elias Martin',
    check_for_async=False
)

# Step 4: Define the subreddit
subreddit = reddit.subreddit('changemyview')


# Step 5: Save the posts
# Create lists to store data
titles = []
bodies = []
urls = []
comments_list = []

# Iterate over the posts
for submission in subreddit.new(limit=10):  # Adjust the limit as needed
    submission.comments.replace_more(limit=0)  # Remove MoreComments
    comments = submission.comments.list()[:10]  # Get top 10 comments

    # Append data to lists
    titles.append(submission.title)
    bodies.append(submission.selftext)
    urls.append(submission.url)
    comments_list.append([comment.body for comment in comments])

# Creating a DataFrame
df = pd.DataFrame({
    'Title': titles,
    'Body': bodies,
    'URL': urls,
    'Top Comments': comments_list
})

print(df)
# Saving the df
df.to_csv('Reddit.csv', index=False)